import os
from datetime import datetime
import pandas as pd
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
import plotly.io as pio

class AIReportGenerator:
    """
    Generates a professional PDF report for a given ticker.
    Includes:
    - Executive Summary
    - Technical Analysis
    - Fundamental Overview
    - Quant Analysis
    """
    
    def __init__(self):
        self.styles = getSampleStyleSheet()
        self.title_style = self.styles['Heading1']
        self.normal_style = self.styles['BodyText']
        
    def generate_report(self, ticker: str, data: dict, output_path: str = None) -> str:
        """
        Generate a PDF report.
        data: dictionary containing 'price', 'rsi', 'pe', 'recommendation', etc.
        """
        if not output_path:
            output_path = f"{ticker}_Report_{datetime.now().strftime('%Y%m%d')}.pdf"
            
        doc = SimpleDocTemplate(output_path, pagesize=letter)
        elements = []
        
        # --- Title ---
        elements.append(Paragraph(f"Investment Report: {ticker}", self.title_style))
        elements.append(Spacer(1, 12))
        elements.append(Paragraph(f"Date: {datetime.now().strftime('%Y-%m-%d')}", self.normal_style))
        elements.append(Spacer(1, 24))
        
        # --- Executive Summary ---
        elements.append(Paragraph("Executive Summary", self.styles['Heading2']))
        summary_text = f"""
        <b>{ticker}</b> is currently trading at <b>${data.get('price', 'N/A')}</b>. 
        Based on our analysis, the technical posture is <b>{data.get('tech_posture', 'Neutral')}</b> 
        while fundamentals appear <b>{data.get('fund_posture', 'Stable')}</b>.
        <br/><br/>
        <b>AI Recommendation:</b> {data.get('recommendation', 'HOLD')}
        """
        elements.append(Paragraph(summary_text, self.normal_style))
        elements.append(Spacer(1, 12))
        
        # --- Technicals ---
        elements.append(Paragraph("Technical Analysis", self.styles['Heading2']))
        tech_data = [
            ['Metric', 'Value', 'Signal'],
            ['RSI (14)', f"{data.get('rsi', 50):.2f}", 'Bullish' if data.get('rsi', 50) > 50 else 'Bearish'],
            ['Trend (SMA)', data.get('trend', 'Neutral'), 'Neutral'],
            ['Volatility', f"{data.get('volatility', 0):.2%}", 'Low' if data.get('volatility', 0) < 0.2 else 'High']
        ]
        t = Table(tech_data)
        t.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.grey),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
            ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
            ('GRID', (0, 0), (-1, -1), 1, colors.black)
        ]))
        elements.append(t)
        elements.append(Spacer(1, 12))
        
        # --- Fundamentals ---
        elements.append(Paragraph("Fundamental Overview", self.styles['Heading2']))
        fund_text = f"""
        The company has a Market Cap of <b>{data.get('market_cap', 'N/A')}</b> and a P/E Ratio of <b>{data.get('pe', 'N/A')}</b>.
        Sector average P/E is typically around 20-25x.
        """
        elements.append(Paragraph(fund_text, self.normal_style))
        
        # --- Disclaimer ---
        elements.append(Spacer(1, 48))
        disclaimer = """
        <i>Disclaimer: This report is generated by an AI Agent for informational purposes only. 
        It does not constitute financial advice. Please do your own due diligence.</i>
        """
        elements.append(Paragraph(disclaimer, self.styles['Italic']))
        
        doc.build(elements)
        return output_path
